---

- name: Configure PostgreSQL extensions
  become: true
  become_user: "{{ postgresql_user }}"
  community.postgresql.postgresql_ext:
    name: "{{ item.name }}"
    db: "{{ item.db }}"
    schema: "{{ item.schema | default(omit) }}"
    cascade: "{{ item.cascade | default(omit) }}"
    version: "{{ item.version | default(omit) }}"
    login_host: "{{ item.login_host | default('localhost') }}"
    login_password: "{{ item.login_password | default(omit) }}"
    login_user: "{{ item.login_user | default(postgresql_user) }}"
    login_unix_socket: "{{ item.login_unix_socket | default(postgresql_unix_socket_directories[0]) }}"
    port: "{{ item.port | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ postgresql_extensions }}"
  tags: ["extensions"]
