---
# Variable configuration.
- ansible.builtin.include_tasks: variables.yml

# Setup/install tasks.
- ansible.builtin.include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags: ["install"]

- ansible.builtin.include_tasks: setup-Archlinux.yml
  when: ansible_os_family == 'Archlinux'
  tags: ["install"]

- ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'
  tags: ["install"]

- ansible.builtin.include_tasks: initialize.yml
  tags: ["install"]

- ansible.builtin.include_tasks: configure.yml
  tags: ["configure"]

- ansible.builtin.include_tasks: setup-ssl.yml
  when: postgresql_setup_ssl | bool
  tags: ["ssl"]

- ansible.builtin.include_tasks: logging.yml
  tags: ["logging"]

- name: Ensure PostgreSQL is started and enabled on boot.
  ansible.builtin.service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_service_state }}"
    enabled: "{{ postgresql_service_enabled }}"

# Configure PostgreSQL.
- ansible.builtin.import_tasks: users.yml
- ansible.builtin.import_tasks: databases.yml
- ansible.builtin.import_tasks: extensions.yml
- ansible.builtin.import_tasks: users_props.yml
