---
# Variable configuration.
- name: Include variables
  ansible.builtin.include_tasks: variables.yml

# Setup/install tasks.
- name: Include RedHat install tasks
  ansible.builtin.include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags: ["install"]

- name: Include Arch install tasks
  ansible.builtin.include_tasks: setup-Archlinux.yml
  when: ansible_os_family == 'Archlinux'
  tags: ["install"]

- name: Include Debian install tasks
  ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'
  tags: ["install"]

- name: Include initialization tasks
  ansible.builtin.include_tasks: initialize.yml
  tags: ["install"]

- name: Include configuration tasks
  ansible.builtin.include_tasks: configure.yml
  tags: ["configure"]

- name: Include SSL tasks
  ansible.builtin.include_tasks: setup-ssl.yml
  when: postgresql_setup_ssl | bool
  tags: ["ssl"]

- name: Include logging tasks
  ansible.builtin.include_tasks: logging.yml
  tags: ["logging"]

- name: Ensure PostgreSQL is started and enabled on boot.
  ansible.builtin.service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_service_state }}"
    enabled: "{{ postgresql_service_enabled }}"

# Configure PostgreSQL.
- name: Import user tasks
  ansible.builtin.import_tasks: users.yml

- name: Import database tasks
  ansible.builtin.import_tasks: databases.yml

- name: Import extension tasks
  ansible.builtin.import_tasks: extensions.yml

- name: Import user props tasks
  ansible.builtin.import_tasks: users_props.yml
