---
# Variable configuration.
- include_tasks: variables.yml

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags: ["install"]

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'
  tags: ["install"]

- include_tasks: initialize.yml
  tags: ["install"]

- include_tasks: configure.yml
  tags: ["configure"]

- include_tasks: setup-ssl.yml
  when: postgresql_setup_ssl | bool
  tags: ["ssl"]

- name: Ensure PostgreSQL is started and enabled on boot.
  service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_service_state }}"
    enabled: "{{ postgresql_service_enabled }}"

# Configure PostgreSQL.
- import_tasks: users.yml
- import_tasks: databases.yml
- import_tasks: extensions.yml
- import_tasks: users_props.yml
