---

- name: Configure memberships
  community.postgresql.postgresql_membership:
    login_host: "{{ item.login_host | default('localhost') }}"
    login_password: "{{ item.login_password | default(omit) }}"
    login_user: "{{ item.login_user | default(postgresql_user) }}"
    login_unix_socket: "{{ item.login_unix_socket | default(postgresql_unix_socket_directories[0]) }}"
    port: "{{ item.port | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    groups: "{{ item.groups }}"
    target_roles: "{{ item.target_roles }}"
    fail_on_role: "{{ item.fail_on_role | default(omit) }}"
  with_items: "{{ postgresql_memberships }}"
  become: true
  become_user: "{{ postgresql_user }}"
  vars:
    ansible_ssh_pipelining: true
  tags: ["membership"]
