---

- name: Configure privileges
  community.postgresql.postgresql_privs:
    database: "{{ item.database }}"
    login_host: "{{ item.login_host | default('localhost') }}"
    login_password: "{{ item.login_password | default(omit) }}"
    login_user: "{{ item.login_user | default(postgresql_user) }}"
    login_unix_socket: "{{ item.login_unix_socket | default(postgresql_unix_socket_directories[0]) }}"
    port: "{{ item.port | default(omit) }}"
    objs: "{{ item.objs | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    privs: "{{ item.privs | default(omit) }}"
    type: "{{ item.type | default(omit) }}"
    roles: "{{ item.roles }}"
    target_roles: "{{ item.target_roles | default(omit) }}"
    grant_option: "{{ item.grant_option | default(omit) }}"
  with_items: "{{ postgresql_privileges }}"
  become: true
  become_user: "{{ postgresql_user }}"
  vars:
    ansible_ssh_pipelining: true
  tags: ["privs"]
