---

- name: Copy CA
  ansible.builtin.copy:
    src: "{{ postgresql_ssl_ca_path }}"
    owner: "root"
    group: "{{ postgresql_group }}"
    dest: "{{ postgresql_data_dir }}/root.crt"
    mode: "0644"
  when: postgresql_ssl_ca_path | length > 0
  notify: Reload postgresql

- name: Copy cert
  ansible.builtin.copy:
    src: "{{ postgresql_ssl_cert_path }}"
    owner: "root"
    group: "{{ postgresql_group }}"
    dest: "{{ postgresql_data_dir }}/server.crt"
    mode: "0644"
  when: postgresql_ssl_cert_path | length > 0
  notify: Reload postgresql

- name: Copy private key
  ansible.builtin.copy:
    src: "{{ postgresql_ssl_key_path }}"
    owner: "root"
    group: "{{ postgresql_group }}"
    dest: "{{ postgresql_data_dir }}/server.key"
    mode: "0644"
  when: postgresql_ssl_key_path | length > 0
  notify: Reload postgresql
